"""empty message

Revision ID: 04566c98d0d8
Revises: 418c8b4e4c3d
Create Date: 2021-12-19 00:27:13.851037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04566c98d0d8'
down_revision = '418c8b4e4c3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
